import { Column, Entity, Index, ManyToOne, JoinColumn, Unique } from 'typeorm';
import { UuidEntity } from './base.entity';
import { User } from './user.entity';
import { Lesson } from './lesson.entity';
import { Certificate } from './certificate.entity';
import { ExamAttempt } from './exam-attempt.entity';
import { PromoCode } from './promo-code.entity';

// ── StudentProgress ──────────────────────────────────────────────────────────

@Entity('student_progress')
@Unique(['userId', 'lessonId'])
export class StudentProgress extends UuidEntity {
  @Index()
  @Column({ type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, (u) => u.progress, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Index()
  @Column({ type: 'uuid' })
  lessonId: string;

  @ManyToOne(() => Lesson, (l) => l.studentProgress, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'lesson_id' })
  lesson: Lesson;

  @Column({ type: 'timestamptz' })
  completedAt: Date;
}

// ── IssuedCertificate ────────────────────────────────────────────────────────

@Entity('issued_certificates')
export class IssuedCertificate extends UuidEntity {
  /**
   * Globally unique cert ID: IOS-{PROGRAM_CODE}-{YEAR}-{6-digit-seq}.
   * Generated by DB trigger set_cert_sequence.
   * Separate from the UUID primary key — this is the public-facing identifier
   * shown on certificates and in /verify/:certId URLs.
   */
  @Index({ unique: true })
  @Column({ type: 'varchar', length: 50, nullable: true })
  certId: string | null;

  @Index()
  @Column({ type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, (u) => u.issuedCertificates, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column({ type: 'uuid' })
  certificateId: string;

  @ManyToOne(() => Certificate, (c) => c.issuedCertificates, {
    onDelete: 'CASCADE',
  })
  @JoinColumn({ name: 'certificate_id' })
  certificate: Certificate;

  @Column({ type: 'uuid' })
  examAttemptId: string;

  @ManyToOne(() => ExamAttempt, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'exam_attempt_id' })
  examAttempt: ExamAttempt;

  @Column({ type: 'varchar', length: 500, nullable: true })
  s3Url: string | null;

  @Column({ type: 'varchar', length: 500, nullable: true })
  qrUrl: string | null;

  @Column({ type: 'boolean', default: true })
  isActive: boolean;

  @Column({ type: 'timestamptz' })
  issuedAt: Date;
}

// ── Transaction ──────────────────────────────────────────────────────────────

export enum TransactionStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  FAILED = 'failed',
  REFUNDED = 'refunded',
}

@Entity('transactions')
export class Transaction extends UuidEntity {
  @Index()
  @Column({ type: 'uuid' })
  userId: string;

  @ManyToOne(() => User, (u) => u.transactions, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'user_id' })
  user: User;

  @Column({ type: 'uuid' })
  certId: string;

  @ManyToOne(() => Certificate, (c) => c.transactions, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'cert_id' })
  certificate: Certificate;

  @Index({ unique: true })
  @Column({ type: 'varchar', length: 255 })
  stripeSessionId: string;

  @Column({ type: 'numeric', precision: 10, scale: 2 })
  amount: number;

  @Column({ type: 'varchar', length: 3, default: 'USD' })
  currency: string;

  @Column({
    type: 'enum',
    enum: TransactionStatus,
    default: TransactionStatus.PENDING,
  })
  status: TransactionStatus;

  @Column({ type: 'uuid', nullable: true })
  promoCodeId: string | null;

  @ManyToOne(() => PromoCode, { nullable: true, onDelete: 'SET NULL' })
  @JoinColumn({ name: 'promo_code_id' })
  promoCode: PromoCode | null;
}
